### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by tylermercer** [FractalFir/FractalFir.github.io#1]
>  join me on my adventures, as we find whacky ways to do things, we probably would be better off not doing!

I totally would, if there was an RSS feed. 😀 Thoroughly enjoyed your "Compiling Rust for .NET" article.

**Comment by FractalFir** [comment]
I am glad you enjoyed it.
I will look into setting up an RSS feed. It should not be too difficult, but may take some time, since I want to ensure everything works as expected(I don't want to, for example, accidentally spam people's feeds due to bugs).

**Comment by FractalFir** [comment]
I have added [an RSS feed](https://fractalfir.github.io/generated_html/rss.xml).

**Comment by tylermercer** [comment]
Subscribed!
